services:
  db:
    image: postgres
    container_name: pg-db
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 4294967296 # 4096*2^20 bytes = 4Gb
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "127.0.0.1:5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    volumes:
      - ./data/minio-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server /data --console-address ":9001"
    # networks:
    #   miniostorage:
    #     aliases:
    #       - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 180s
      timeout: 20s
      retries: 3
      start_period: 60s

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"
    command: redis-server --requirepass ${KV_PASSWORD}
