# configuration for https://github.com/MarcoIeni/release-plz

[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# enable changelog updates
changelog_update = true
# update dependencies with `cargo update`
dependencies_update = true
# create tags for the releases
git_tag_enable = true
# disable GitHub releases
git_release_enable = false
# labels for the release PR
pr_labels = ["release"]
pr_name = "Release v{{ version }}"
# disallow updating repositories with uncommitted changes
allow_dirty = true
# disallow packaging with uncommitted changes
publish_allow_dirty = true
# disable running `cargo-semver-checks`
semver_check = true

[[package]]
name = "mito"
changelog_include = ["netmito"]

[[package]]
name = "netmito"
changelog_update = false
