//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::active_tasks::Entity as ActiveTasks;
pub use super::agents::Entity as Agents;
pub use super::archived_tasks::Entity as ArchivedTasks;
pub use super::artifacts::Entity as Artifacts;
pub use super::attachments::Entity as Attachments;
pub use super::group_agent::Entity as GroupAgent;
pub use super::group_worker::Entity as GroupWorker;
pub use super::groups::Entity as Groups;
pub use super::hook_task::Entity as HookTasks;
pub use super::machines::Entity as Machines;
pub use super::suite_agent_jobs::Entity as SuiteAgentJobs;
pub use super::task_suite_agent::Entity as TaskSuiteAgent;
pub use super::task_suites::Entity as TaskSuites;
pub use super::user_group::Entity as UserGroup;
pub use super::users::Entity as Users;
pub use super::workers::Entity as Workers;
